<?xml version="1.0"?>
<robot>
     <macro name="cylinder_inertia" params="m r h">
        <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                  iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                  izz="${m*r*r/2}" />
      </macro>

      <macro name="box_inertia" params="m x y z">
        <inertia  iyy="${m*(y*y+z*z)/12}" ixy = "0" ixz = "0"
                  izz="${m*(x*x+y*y)/12}" iyz = "0"
                  ixx="${m*(x*x+z*z)/12}" />
      </macro>

      <macro name="sphere_inertia" params="m r">
        <inertia  ixx="${2*m*r*r/5}" ixy = "0" ixz = "0"
                  iyy="${2*m*r*r/5}" iyz = "0"
                  izz="${2*m*r*r/5}" />
      </macro>

     <macro name="wheel" params="lr tY">

      <link name="${lr}_wheel">

         <visual>
           <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
           <geometry>
             <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
           </geometry>
           <material name="black"/>
         </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <geometry>
            <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
          </geometry>
    
        </collision>

        <inertial>
          <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}" />
          <mass value="${wheelMass}"/>
          <cylinder_inertia m="${wheelMass}" r="${wheelRadius}" h="${wheelWidth}"/>
        </inertial>
      </link>

        <gazebo reference="${lr}_wheel">
          <material>Gazebo/Black</material>
            <mu1 value="100.0" />
            <mu2 value="100.0" />
            <kp  value="1000000.0" />
            <kd  value="1.0" />
        </gazebo>

       <joint name="${lr}_wheel_hinge" type="continuous">
          <parent link="chassis"/>
          <child link="${lr}_wheel"/>
          <origin xyz="-${+wheelPos-chassisLength/4} ${tY*wheelWidth/2+tY*chassisWidth/2} ${wheelRadius}" rpy="0 0 0" />
          <axis xyz="0 1 0" rpy="0 0 0" />
          <limit effort="30" velocity="30"/>
          <joint_properties damping="0" friction="0"/> 
        </joint>

        <transmission name="${lr}_trans">
          <type>transmission_interface/SimpleTransmission</type>
          <joint name="${lr}_wheel_hinge">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
          </joint>
          <actuator name="${lr}_motor">
            <hardwareInterface>PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
          </actuator>
        </transmission>

     </macro>
</robot>